// SVITA — Plan otwarcia gabinetu stomatologicznego w Polsce
// PIVOT 2026-04-12: dental PL only. Languages: PL + EN + BE + UK.
// All claims must be verifiable. No "30%", no "1 hour", no fake stats.

window.LABS67_DEFAULT_LANG = 'pl';

window.I18N = {

// ── NAV ──
nav_what:        { pl:"Co dostajesz",   en:"What you get",   be:"Што атрымліваеш", uk:"Що отримуєш" },
nav_case:        { pl:"Case Świtlicy",  en:"Świtlica case",  be:"Кейс Świtlica",   uk:"Кейс Świtlica" },
nav_pricing:     { pl:"Cennik",         en:"Pricing",        be:"Цэны",            uk:"Ціни" },
nav_faq:         { pl:"FAQ",            en:"FAQ",            be:"FAQ",             uk:"FAQ" },
nav_login:       { pl:"Zaloguj",        en:"Log in",         be:"Увайсці",         uk:"Увійти" },
nav_start:       { pl:"Zacznij plan",   en:"Start plan",     be:"Пачаць план",     uk:"Почати план" },

// ── HERO ──
hero_badge:      { pl:"Tylko stomatologia · tylko Polska · zweryfikowane dane 2026",
                   en:"Dentistry only · Poland only · verified 2026 data",
                   be:"Толькі стаматалогія · толькі Польшча · правераныя дадзеныя 2026",
                   uk:"Лише стоматологія · лише Польща · перевірені дані 2026" },
hero_title:      { pl:"Plan otwarcia gabinetu stomatologicznego <span class=\"gradient\">w Polsce</span>",
                   en:"Plan for opening a dental practice <span class=\"gradient\">in Poland</span>",
                   be:"План адкрыцця стаматалагічнага кабінета <span class=\"gradient\">у Польшчы</span>",
                   uk:"План відкриття стоматологічного кабінету <span class=\"gradient\">у Польщі</span>" },
hero_desc:       { pl:"Realne ceny sprzętu od polskich dystrybutorów. Pensje brutto 2026 według województwa. Lista dokumentów NFZ, sanepid, RTG. Gotowy budżet startu i prognoza ROI w 14 dni — albo zwracamy pieniądze.",
                   en:"Real equipment prices from Polish distributors. Gross 2026 salaries by voivodeship. Document checklist for NFZ, sanepid, X-ray license. Startup budget and ROI forecast in 14 days — or your money back.",
                   be:"Рэальныя цэны абсталявання ад польскіх дыстрыб'ютараў. Брутта зарплаты 2026 па ваяводствах. Спіс дакументаў NFZ, sanepid, RTG. Гатовы стартавы бюджэт і прагноз ROI за 14 дзён — або вяртаем грошы.",
                   uk:"Реальні ціни обладнання від польських дистриб'юторів. Зарплати брутто 2026 за воєводствами. Список документів NFZ, sanepid, RTG. Готовий стартовий бюджет і прогноз ROI за 14 днів — або повертаємо гроші." },
hero_cta:        { pl:"Zamów plan — 199 €",   en:"Order the plan — €199",
                   be:"Замовіць план — 199 €", uk:"Замовити план — 199 €" },
hero_cta_sub:    { pl:"Jednorazowa płatność. Bez subskrypcji.",
                   en:"One-time payment. No subscription.",
                   be:"Аднаразовы плацёж. Без падпіскі.",
                   uk:"Разовий платіж. Без підписки." },

// ── HONEST STATUS BAR ──
status_clients:  { pl:"Klientów dzisiaj", en:"Clients today", be:"Кліентаў сёння", uk:"Клієнтів сьогодні" },
status_clients_v:{ pl:"1 (Świtlica — nasza)", en:"1 (Świtlica — ours)",
                   be:"1 (Świtlica — наша)", uk:"1 (Świtlica — наша)" },
status_db:       { pl:"Zweryfikowane pozycje sprzętu", en:"Verified equipment items",
                   be:"Правераныя пазіцыі абсталявання", uk:"Перевірені позиції обладнання" },
status_db_v:     { pl:"50+ na 2026-04", en:"50+ as of 2026-04",
                   be:"50+ на 2026-04", uk:"50+ станом на 2026-04" },
status_country:  { pl:"Pokrycie", en:"Coverage", be:"Ахоп", uk:"Покриття" },
status_country_v:{ pl:"Polska", en:"Poland", be:"Польшча", uk:"Польща" },

// ── WHAT YOU GET ──
what_label:      { pl:"Co dostajesz", en:"What you get", be:"Што атрымліваеш", uk:"Що отримуєш" },
what_title:      { pl:"6 rozdziałów twojego planu", en:"6 chapters of your plan",
                   be:"6 раздзелаў твайго плану", uk:"6 розділів твого плану" },
what_sub:        { pl:"Każdy rozdział to konkretne liczby, źródła i lista zakupów — nie ogólniki.",
                   en:"Every chapter has concrete numbers, sources and shopping lists — no fluff.",
                   be:"Кожны раздзел — гэта канкрэтныя лічбы, крыніцы і спіс закупак — без агульных слоў.",
                   uk:"Кожен розділ — це конкретні числа, джерела та список закупівель — без загальних фраз." },

w1_t: { pl:"1. Lokal", en:"1. Premises", be:"1. Памяшканне", uk:"1. Приміщення" },
w1_d: { pl:"Metraż minimum dla NFZ, układ pomieszczeń, wymagania sanepid, średnia stawka czynszu w wybranym mieście (źródło: otodom.pl, gumtree, raporty Colliers 2026).",
        en:"Minimum area for NFZ, room layout, sanepid requirements, average rent in your city (sources: otodom.pl, Gumtree, Colliers 2026 reports).",
        be:"Мінімальная плошча для NFZ, планаванне пакояў, патрабаванні sanepid, сярэдняя стаўка арэнды ў твім горадзе (крыніцы: otodom.pl, Gumtree, справаздачы Colliers 2026).",
        uk:"Мінімальна площа для NFZ, планування приміщень, вимоги sanepid, середня орендна ставка у твоєму місті (джерела: otodom.pl, Gumtree, звіти Colliers 2026)." },

w2_t: { pl:"2. Zespół i ZUS", en:"2. Team and payroll", be:"2. Каманда і ZUS", uk:"2. Команда і ZUS" },
w2_d: { pl:"Stomatolog, asystent, higienistka, recepcjonista — pensje brutto 2026 z pracuj.pl + składki ZUS i PIT. Gotowe ogłoszenia do publikacji.",
        en:"Dentist, assistant, hygienist, receptionist — gross 2026 salaries from pracuj.pl + ZUS and PIT contributions. Ready-to-publish job posts.",
        be:"Стаматолаг, асістэнт, гігіеністка, рэцэпцыяніст — брутта зарплаты 2026 з pracuj.pl + узносы ZUS і PIT. Гатовыя аб'явы для публікацыі.",
        uk:"Стоматолог, асистент, гігієніст, рецепціоніст — зарплати брутто 2026 з pracuj.pl + внески ZUS і PIT. Готові оголошення для публікації." },

w3_t: { pl:"3. Sprzęt — realni dostawcy", en:"3. Equipment — real suppliers",
        be:"3. Абсталяванне — рэальныя пастаўшчыкі", uk:"3. Обладнання — реальні постачальники" },
w3_d: { pl:"Unit dentystyczny, RTG, autoklaw, lampa polimeryzacyjna, fotel — ceny KaVo Polska, Planmeca PL, Dentsply Sirona PL, Henry Schein. Gwarancja, czas dostawy, kontakty handlowca.",
        en:"Dental unit, X-ray, autoclave, curing light, chair — prices from KaVo Polska, Planmeca PL, Dentsply Sirona PL, Henry Schein. Warranty, lead time, sales contact.",
        be:"Стаматалагічны юніт, RTG, аўтаклаў, палімерызацыйная лямпа, крэсла — цэны KaVo Polska, Planmeca PL, Dentsply Sirona PL, Henry Schein. Гарантыя, тэрмін пастаўкі, кантакты гандляра.",
        uk:"Стоматологічний юніт, RTG, автоклав, полімеризаційна лампа, крісло — ціни KaVo Polska, Planmeca PL, Dentsply Sirona PL, Henry Schein. Гарантія, термін постачання, контакти продавця." },

w4_t: { pl:"4. Dokumenty i licencje", en:"4. Documents and licenses",
        be:"4. Дакументы і ліцэнзіі", uk:"4. Документи і ліцензії" },
w4_d: { pl:"Wpis do rejestru podmiotów leczniczych, zezwolenie na promieniowanie (RTG) z PAA, decyzja sanepidu, RIDO, RODO. Wzory wniosków + kontakty urzędów dla twojego województwa.",
        en:"Entry into the register of medical entities, X-ray license from PAA, sanepid decision, RIDO, RODO. Application templates + office contacts for your voivodeship.",
        be:"Запіс у рэестр медыцынскіх установаў, дазвол на выпраменьванне (RTG) ад PAA, рашэнне sanepid, RIDO, RODO. Узоры заяў + кантакты ўстаноў для твайго ваяводства.",
        uk:"Внесення до реєстру медичних суб'єктів, дозвіл на випромінювання (RTG) від PAA, рішення sanepid, RIDO, RODO. Шаблони заяв + контакти установ для твого воєводства." },

w5_t: { pl:"5. Budżet startu", en:"5. Startup budget",
        be:"5. Стартавы бюджэт", uk:"5. Стартовий бюджет" },
w5_d: { pl:"Rozbicie pozycja po pozycji: lokal, remont, sprzęt, dokumenty, marketing, rezerwa płynności na 3 miesiące. PLN, podatki uwzględnione.",
        en:"Line-by-line breakdown: premises, fit-out, equipment, documents, marketing, 3-month liquidity reserve. PLN, taxes included.",
        be:"Разбіўка па пазіцыях: памяшканне, рамонт, абсталяванне, дакументы, маркетынг, рэзерв ліквіднасці на 3 месяцы. PLN, з падаткамі.",
        uk:"Розбивка за позиціями: приміщення, ремонт, обладнання, документи, маркетинг, резерв ліквідності на 3 місяці. PLN, з податками." },

w6_t: { pl:"6. ROI i rentowność", en:"6. ROI and profitability",
        be:"6. ROI і рэнтабельнасць", uk:"6. ROI і рентабельність" },
w6_d: { pl:"Założenia: liczba pacjentów / dzień, średni koszyk, marża. Próg rentowności w miesiącach. Wrażliwość na ±20% w cenach i obłożeniu.",
        en:"Assumptions: patients/day, average ticket, margin. Break-even in months. Sensitivity to ±20% on prices and occupancy.",
        be:"Дапушчэнні: пацыентаў/дзень, сярэдні чэк, маржа. Парог рэнтабельнасці ў месяцах. Адчувальнасць да ±20% па цэнах і загрузцы.",
        uk:"Припущення: пацієнтів/день, середній чек, маржа. Точка беззбитковості в місяцях. Чутливість до ±20% за цінами і завантаженням." },

// ── HONESTY ──
honesty_label:   { pl:"Co tu nie jest sprzedażą", en:"What we won't sell you",
                   be:"Чаго мы не прадаём", uk:"Чого ми не продаємо" },
honesty_title:   { pl:"Czego ten plan nie zrobi", en:"What this plan won't do",
                   be:"Чаго гэты план не зробіць", uk:"Що цей план не зробить" },
honesty_sub:     { pl:"Jesteśmy nowym narzędziem. Chcemy żebyś wiedział na co się piszesz.",
                   en:"We're a new tool. You should know what you're getting.",
                   be:"Мы новы інструмент. Хочам каб ты ведаў на што запісваешся.",
                   uk:"Ми новий інструмент. Хочемо щоб ти знав на що погоджуєшся." },
h1_t: { pl:"To nie zastąpi prawnika", en:"It won't replace a lawyer",
        be:"Гэта не заменіць юрыста", uk:"Це не замінить юриста" },
h1_d: { pl:"Każdy dokument trzeba podpisać u notariusza i sprawdzić u radcy prawnego. Plan zawiera szablony i listę kontaktów — nie poradę prawną.",
        en:"Every document needs notarization and a lawyer's review. The plan has templates and contact lists — not legal advice.",
        be:"Кожны дакумент трэба падпісаць у натарыуса і праверыць у прававога саветніка. План змяшчае шаблоны і кантакты — не юрыдычную параду.",
        uk:"Кожен документ треба підписати у нотаріуса та перевірити у юриста. План містить шаблони і контакти — не юридичну пораду." },
h2_t: { pl:"Ceny mogą się zmienić", en:"Prices may shift",
        be:"Цэны могуць змяніцца", uk:"Ціни можуть змінитися" },
h2_d: { pl:"Wszystkie liczby pochodzą z konkretnych ofert na 2026-04. Sprzęt podrożeje albo stanieje — w planie podajesz datę i źródło każdej pozycji.",
        en:"Every number comes from a real 2026-04 offer. Equipment prices will move — every line item shows the date and source.",
        be:"Усе лічбы з канкрэтных прапаноў на 2026-04. Абсталяванне падаражэе ці падзешавее — у плане паказана дата і крыніца кожнай пазіцыі.",
        uk:"Усі числа з конкретних пропозицій на 2026-04. Обладнання подорожчає або подешевшає — у плані вказано дату і джерело кожної позиції." },
h3_t: { pl:"Nie wystawiamy faktur", en:"We don't sell equipment",
        be:"Мы не прадаём абсталяванне", uk:"Ми не продаємо обладнання" },
h3_d: { pl:"Nie sprzedajemy sprzętu, nie wynajmujemy lokali, nie zatrudniamy ludzi za ciebie. Linkujemy bezpośrednio do producentów i pośredników.",
        en:"We don't sell equipment, lease premises or hire people for you. We link directly to manufacturers and brokers.",
        be:"Мы не прадаём абсталяванне, не здаём памяшканні, не наймаем людзей за цябе. Спасылаемся напроста на вытворцаў і пасярэднікаў.",
        uk:"Ми не продаємо обладнання, не здаємо приміщення, не наймаємо людей за тебе. Посилаємось напряму на виробників і посередників." },

// ── ŚWITLICA CASE ──
case_label:      { pl:"Pierwszy klient", en:"First client",
                   be:"Першы кліент", uk:"Перший клієнт" },
case_title:      { pl:"Świtlica — nasza własna klinika w Bydgoszczy",
                   en:"Świtlica — our own clinic in Bydgoszcz",
                   be:"Świtlica — наша ўласная клініка ў Быдгашчы",
                   uk:"Świtlica — наша власна клініка у Бидгощі" },
case_sub:        { pl:"Zanim zaczęliśmy sprzedawać plan innym, użyliśmy go u siebie. Wszystkie liczby poniżej są prawdziwe i sprawdzalne.",
                   en:"Before selling the plan to others, we used it on ourselves. Every number below is real and verifiable.",
                   be:"Перш чым прадаваць план іншым, мы выкарысталі яго ў сябе. Усе лічбы ніжэй сапраўдныя і праверныя.",
                   uk:"Перш ніж продавати план іншим, ми використали його у себе. Усі числа нижче справжні і перевірні." },
case_budget:     { pl:"Planowany budżet", en:"Planned budget",
                   be:"Плануемы бюджэт", uk:"Планований бюджет" },
case_budget_v:   { pl:"~1 760 000 PLN", en:"~1,760,000 PLN",
                   be:"~1 760 000 PLN", uk:"~1 760 000 PLN" },
case_open:       { pl:"Planowane otwarcie", en:"Planned opening",
                   be:"Плануемае адкрыццё", uk:"Планове відкриття" },
case_open_v:     { pl:"Wrzesień 2026", en:"September 2026",
                   be:"Верасень 2026", uk:"Вересень 2026" },
case_city:       { pl:"Miasto", en:"City", be:"Горад", uk:"Місто" },
case_city_v:     { pl:"Bydgoszcz", en:"Bydgoszcz", be:"Быдгашч", uk:"Бидгощ" },
case_format:     { pl:"Format", en:"Format", be:"Фармат", uk:"Формат" },
case_format_v:   { pl:"3 fotele, NFZ + prywatnie", en:"3 chairs, NFZ + private",
                   be:"3 крэслы, NFZ + прыватна", uk:"3 крісла, NFZ + приватно" },
case_link:       { pl:"Pobierz nasz pełny plan (PDF) →", en:"Download our full plan (PDF) →",
                   be:"Спампуй наш поўны план (PDF) →", uk:"Завантаж наш повний план (PDF) →" },
case_warning:    { pl:"⚠️ Świtlica jeszcze się nie otworzyła. Aktualizujemy ten plan w miarę postępów. To uczciwy work-in-progress, nie marketing.",
                   en:"⚠️ Świtlica hasn't opened yet. We update this plan as we go. Honest work-in-progress, not marketing.",
                   be:"⚠️ Świtlica яшчэ не адкрылася. Мы абнаўляем гэты план па меры прагрэсу. Гэта сумленны work-in-progress, не маркетынг.",
                   uk:"⚠️ Świtlica ще не відкрилася. Ми оновлюємо цей план у міру прогресу. Це чесний work-in-progress, не маркетинг." },

// ── PRICING ──
pricing_label:   { pl:"Cennik", en:"Pricing", be:"Цэны", uk:"Ціни" },
pricing_title:   { pl:"Jeden plan. Jedna płatność.", en:"One plan. One payment.",
                   be:"Адзін план. Адзін плацёж.", uk:"Один план. Один платіж." },
pricing_sub:     { pl:"Bez subskrypcji, bez triala 5 zapytań dziennie, bez taryf PRO/UNLIMITED. Płacisz raz, plan jest twój na zawsze.",
                   en:"No subscriptions, no 5-questions-a-day trials, no PRO/UNLIMITED tiers. Pay once, the plan is yours forever.",
                   be:"Без падпісак, без трыяла 5 запытаў на дзень, без тарыфаў PRO/UNLIMITED. Плаціш раз, план твой назаўжды.",
                   uk:"Без підписок, без тріалу 5 запитів на день, без тарифів PRO/UNLIMITED. Платиш раз, план твій назавжди." },
price_main:      { pl:"199 €", en:"€199", be:"199 €", uk:"199 €" },
price_main_sub:  { pl:"jednorazowo", en:"one-time", be:"аднаразова", uk:"одноразово" },
price_includes:  { pl:"W cenie:", en:"Included:", be:"У кошце:", uk:"У ціні:" },
price_inc1:      { pl:"6 rozdziałów planu z liczbami i źródłami",
                   en:"6 plan chapters with numbers and sources",
                   be:"6 раздзелаў плану з лічбамі і крыніцамі",
                   uk:"6 розділів плану з числами і джерелами" },
price_inc2:      { pl:"Eksport do PDF", en:"PDF export",
                   be:"Экспарт у PDF", uk:"Експорт у PDF" },
price_inc3:      { pl:"Linki do realnych dostawców (KaVo, Planmeca, Henry Schein, Dentsply)",
                   en:"Links to real suppliers (KaVo, Planmeca, Henry Schein, Dentsply)",
                   be:"Спасылкі на рэальных пастаўшчыкоў (KaVo, Planmeca, Henry Schein, Dentsply)",
                   uk:"Посилання на реальних постачальників (KaVo, Planmeca, Henry Schein, Dentsply)" },
price_inc4:      { pl:"Szablony dokumentów NFZ, sanepid, PAA",
                   en:"Document templates: NFZ, sanepid, PAA",
                   be:"Шаблоны дакументаў NFZ, sanepid, PAA",
                   uk:"Шаблони документів NFZ, sanepid, PAA" },
price_inc5:      { pl:"Aktualizacje cen przez 6 miesięcy",
                   en:"Price updates for 6 months",
                   be:"Абнаўленне цэнаў 6 месяцаў",
                   uk:"Оновлення цін 6 місяців" },
price_inc6:      { pl:"Gwarancja zwrotu w 14 dni bez pytań",
                   en:"14-day no-questions money-back guarantee",
                   be:"Гарантыя звароту за 14 дзён без пытанняў",
                   uk:"Гарантія повернення за 14 днів без питань" },
price_upsell_t:  { pl:"+99 € — konsultacja 30 min",
                   en:"+€99 — 30-minute consultation",
                   be:"+99 € — кансультацыя 30 хв",
                   uk:"+99 € — консультація 30 хв" },
price_upsell_d:  { pl:"Zoom z założycielem Świtlicy. Konkretne pytania, konkretne odpowiedzi. Nagranie zostaje u ciebie.",
                   en:"Zoom with Świtlica's founder. Specific questions, specific answers. Recording is yours.",
                   be:"Zoom з заснавальнікам Świtlica. Канкрэтныя пытанні, канкрэтныя адказы. Запіс застаецца ў цябе.",
                   uk:"Zoom із засновником Świtlica. Конкретні питання, конкретні відповіді. Запис залишається у тебе." },
price_cta:       { pl:"Zamów plan", en:"Order the plan",
                   be:"Замовіць план", uk:"Замовити план" },

// ── FAQ ──
faq_label:       { pl:"FAQ", en:"FAQ", be:"FAQ", uk:"FAQ" },
faq_title:       { pl:"Pytania bez ściemy", en:"Questions without BS",
                   be:"Пытанні без ашуканства", uk:"Питання без брехні" },
q1: { pl:"Dlaczego tylko stomatologia w Polsce?",
      en:"Why only dentistry in Poland?",
      be:"Чаму толькі стаматалогія ў Польшчы?",
      uk:"Чому лише стоматологія в Польщі?" },
a1: { pl:"Bo lepiej zrobić jedną niszę uczciwie niż 24 kraje na pół gwizdka. Inne branże dodamy dopiero po 50 płacących klientach w PL.",
      en:"Because doing one niche honestly beats half-baked support for 24 countries. We'll add others only after 50 paying clients in PL.",
      be:"Бо лепш зрабіць адну нішу сумленна, чым 24 краіны напалову. Іншыя галіны дадамо толькі пасля 50 платных кліентаў у PL.",
      uk:"Бо краще зробити одну нішу чесно, ніж 24 країни напівсили. Інші галузі додамо лише після 50 платних клієнтів у PL." },
q2: { pl:"Skąd pewność że ceny są prawdziwe?",
      en:"How do you know the prices are real?",
      be:"Адкуль упэўненасць што цэны сапраўдныя?",
      uk:"Звідки впевненість що ціни справжні?" },
a2: { pl:"Każda pozycja w planie ma datę i źródło: oferta od dystrybutora, mail od handlowca, cennik z 2026-04. Jeśli źródła nie ma — pozycji w planie nie ma.",
      en:"Every line item in the plan shows a date and source: distributor offer, sales email, 2026-04 price list. If there's no source, there's no line.",
      be:"Кожная пазіцыя ў плане мае дату і крыніцу: прапанова дыстрыб'ютара, ліст ад гандляра, прайс-ліст 2026-04. Калі няма крыніцы — няма і пазіцыі ў плане.",
      uk:"Кожна позиція в плані має дату і джерело: пропозиція дистриб'ютора, лист від продавця, прайс 2026-04. Якщо немає джерела — немає і позиції в плані." },
q3: { pl:"Macie inne kliniki które się otworzyły z waszego planu?",
      en:"Do you have other clinics opened with this plan?",
      be:"Ці ёсць у вас іншыя клінікі што адкрыліся па вашым плане?",
      uk:"Чи є у вас інші клініки що відкрилися за вашим планом?" },
a3: { pl:"Nie. Świtlica jest pierwsza i jeszcze się otwiera (wrzesień 2026). Jesteśmy całkowicie nowi i się tego nie wstydzimy.",
      en:"No. Świtlica is first and still opening (September 2026). We're brand new and not hiding it.",
      be:"Не. Świtlica першая і яшчэ адкрываецца (верасень 2026). Мы зусім новыя і не саромеемся гэтага.",
      uk:"Ні. Świtlica перша і ще відкривається (вересень 2026). Ми зовсім нові і цього не приховуємо." },
q4: { pl:"AI wygeneruje mi plan w godzinę?",
      en:"Will the AI generate my plan in an hour?",
      be:"AI згенеруе мне план за гадзіну?",
      uk:"AI згенерує мені план за годину?" },
a4: { pl:"Szkic — tak. Pełny plan z weryfikowanymi liczbami, podpisanymi pytaniami do dostawców i listą dokumentów dla twojego województwa — 14 dni roboczych.",
      en:"Draft — yes. Full plan with verified numbers, supplier inquiries and a per-voivodeship document checklist — 14 business days.",
      be:"Чарнавік — так. Поўны план з праверанымі лічбамі, запытамі да пастаўшчыкоў і спісам дакументаў для твайго ваяводства — 14 працоўных дзён.",
      uk:"Чернетка — так. Повний план з перевіреними числами, запитами до постачальників і списком документів для твого воєводства — 14 робочих днів." },
q5: { pl:"Co jeśli się rozmyślę?",
      en:"What if I change my mind?",
      be:"А калі я перадумаю?",
      uk:"А якщо я передумаю?" },
a5: { pl:"14 dni na zwrot, bez pytań. Piszesz na hello@svita.ai, dostajesz pieniądze z powrotem w 3 dni robocze.",
      en:"14 days for a no-questions refund. Email hello@svita.ai, money back in 3 business days.",
      be:"14 дзён на зварот, без пытанняў. Пішаш на hello@svita.ai, атрымліваеш грошы назад за 3 працоўныя дні.",
      uk:"14 днів на повернення, без питань. Пишеш на hello@svita.ai, отримуєш гроші назад за 3 робочі дні." },
q6: { pl:"Kto za tym stoi?",
      en:"Who's behind this?",
      be:"Хто за гэтым стаіць?",
      uk:"Хто за цим стоїть?" },
a6: { pl:"Artem Wialko, CEO LABS67, Bydgoszcz. Otwiera Świtlicę i równolegle buduje SVITA. Stomatolog-przedsiębiorca, nie startupowiec z prezentacją.",
      en:"Artem Wialko, CEO LABS67, Bydgoszcz. Opening Świtlica and building SVITA in parallel. Dentist-entrepreneur, not a pitch-deck founder.",
      be:"Арцём Вялка, CEO LABS67, Быдгашч. Адкрывае Świtlica і паралельна будуе SVITA. Стаматолаг-прадпрымальнік, не стартапер з прэзентацыяй.",
      uk:"Артем Вялка, CEO LABS67, Бидгощ. Відкриває Świtlica і паралельно будує SVITA. Стоматолог-підприємець, не стартапер з презентацією." },

// ── FOOTER ──
foot_tagline:    { pl:"Jedna nisza. Jedna płatność. Zero ściemy.",
                   en:"One niche. One payment. Zero BS.",
                   be:"Адна ніша. Адзін плацёж. Ніякага ашуканства.",
                   uk:"Одна ніша. Один платіж. Нуль брехні." },

// ── HERO CHAT ──
chat_status:     { pl:"online · gotowe do rozmowy", en:"online · ready to talk",
                   be:"online · гатовы да размовы", uk:"online · готовий до розмови" },
chat_welcome:    { pl:"Cześć! Powiedz w którym mieście chcesz otworzyć gabinet i ile masz foteli — pokażę szybki szkic.",
                   en:"Hi! Tell me which city you're opening in and how many chairs — I'll show a quick sketch.",
                   be:"Прывітанне! Скажы ў якім горадзе хочаш адкрыць кабінет і колькі ў цябе крэслаў — пакажу хуткі чарнавік.",
                   uk:"Привіт! Скажи у якому місті хочеш відкрити кабінет і скільки у тебе крісел — покажу швидку чернетку." },
chat_placeholder:{ pl:"Bydgoszcz, 3 fotele, NFZ + prywatnie",
                   en:"Bydgoszcz, 3 chairs, NFZ + private",
                   be:"Быдгашч, 3 крэслы, NFZ + прыватна",
                   uk:"Бидгощ, 3 крісла, NFZ + приватно" },
chat_analyzing:  { pl:"Analizuję...", en:"Analyzing...",
                   be:"Аналізую...", uk:"Аналізую..." },
chat_cta:        { pl:"Otwórz pełny plan w Dashboard", en:"Open full plan in Dashboard",
                   be:"Адкрыць поўны план у Dashboard", uk:"Відкрити повний план у Dashboard" },
chat_reply_generic: {
  pl:"✓ Analizuję twój gabinet...\n\n📍 Lokal: liczę metraż wg NFZ\n👥 Zespół: pensje brutto 2026 dla twojego województwa\n🛠 Sprzęt: KaVo / Planmeca / Henry Schein z gwarancją\n📋 Dokumenty: NFZ, sanepid, RTG, RIDO\n💰 Budżet: rozbicie pozycja po pozycji\n📈 ROI: próg rentowności w miesiącach\n\nOtwórz Dashboard żeby zobaczyć pełny plan →",
  en:"✓ Analyzing your practice...\n\n📍 Premises: calculating area per NFZ rules\n👥 Team: gross 2026 salaries for your voivodeship\n🛠 Equipment: KaVo / Planmeca / Henry Schein with warranty\n📋 Documents: NFZ, sanepid, X-ray license, RIDO\n💰 Budget: line-by-line breakdown\n📈 ROI: break-even in months\n\nOpen Dashboard to see the full plan →",
  be:"✓ Аналізую твой кабінет...\n\n📍 Памяшканне: лічу плошчу па NFZ\n👥 Каманда: брутта зарплаты 2026 для твайго ваяводства\n🛠 Абсталяванне: KaVo / Planmeca / Henry Schein з гарантыяй\n📋 Дакументы: NFZ, sanepid, RTG, RIDO\n💰 Бюджэт: разбіўка па пазіцыях\n📈 ROI: парог рэнтабельнасці ў месяцах\n\nАдкрый Dashboard каб убачыць поўны план →",
  uk:"✓ Аналізую твій кабінет...\n\n📍 Приміщення: рахую площу за NFZ\n👥 Команда: зарплати брутто 2026 для твого воєводства\n🛠 Обладнання: KaVo / Planmeca / Henry Schein з гарантією\n📋 Документи: NFZ, sanepid, RTG, RIDO\n💰 Бюджет: розбивка за позиціями\n📈 ROI: точка беззбитковості в місяцях\n\nВідкрий Dashboard щоб побачити повний план →"
},

};
