// SVITA Landing — I18N translations for labs67-i18n.js v2.1
// 12 languages: BE DE EN ES FR IT JA KO PL PT RU UK
// Default: EN (set below)
window.LABS67_DEFAULT_LANG = 'en';

window.I18N = {

// ── NAV ──
nav_features: { be:"Магчымасці", de:"Funktionen", en:"Features", es:"Funciones", fr:"Fonctionnalités", it:"Funzionalità", ja:"機能", ko:"기능", pl:"Funkcje", pt:"Recursos", ru:"Возможности", uk:"Можливості" },
nav_how: { be:"Як гэта працуе", de:"So funktioniert's", en:"How it works", es:"Cómo funciona", fr:"Comment ça marche", it:"Come funziona", ja:"仕組み", ko:"작동 방식", pl:"Jak to działa", pt:"Como funciona", ru:"Как это работает", uk:"Як це працює" },
nav_domains: { be:"Дамены", de:"Branchen", en:"Domains", es:"Sectores", fr:"Secteurs", it:"Settori", ja:"業種", ko:"업종", pl:"Branże", pt:"Setores", ru:"Домены", uk:"Домени" },
nav_login: { be:"Увайсці", de:"Anmelden", en:"Log in", es:"Iniciar sesión", fr:"Connexion", it:"Accedi", ja:"ログイン", ko:"로그인", pl:"Zaloguj", pt:"Entrar", ru:"Войти", uk:"Увійти" },
nav_start: { be:"Пачаць бясплатна", de:"Kostenlos starten", en:"Start free", es:"Empezar gratis", fr:"Commencer gratuit", it:"Inizia gratis", ja:"無料で始める", ko:"무료 시작", pl:"Zacznij za darmo", pt:"Começar grátis", ru:"Начать бесплатно", uk:"Почати безкоштовно" },

// ── HERO ──
hero_badge: { be:"AI-канструктар бізнесу", de:"KI-gestützter Business-Konstruktor", en:"AI-powered business constructor", es:"Constructor de negocios con IA", fr:"Constructeur d'entreprise IA", it:"Costruttore di business AI", ja:"AI搭載ビジネス構築ツール", ko:"AI 기반 비즈니스 생성기", pl:"Konstruktor biznesu AI", pt:"Construtor de negócios com IA", ru:"AI-конструктор бизнеса", uk:"AI-конструктор бізнесу" },
hero_title: { be:"Стварыце <span class=\"gradient\">бізнес-канцэпцыю</span> за хвіліны", de:"Erstellen Sie Ihr <span class=\"gradient\">Geschäftskonzept</span> in Minuten", en:"Build your <span class=\"gradient\">business concept</span> in minutes", es:"Crea tu <span class=\"gradient\">concepto de negocio</span> en minutos", fr:"Créez votre <span class=\"gradient\">concept d'entreprise</span> en minutes", it:"Crea il tuo <span class=\"gradient\">concept di business</span> in pochi minuti", ja:"<span class=\"gradient\">ビジネスコンセプト</span>を数分で構築", ko:"<span class=\"gradient\">비즈니스 컨셉</span>을 몇 분 만에 구축", pl:"Stwórz <span class=\"gradient\">koncepcję biznesu</span> w kilka minut", pt:"Crie seu <span class=\"gradient\">conceito de negócio</span> em minutos", ru:"Создайте <span class=\"gradient\">бизнес-концепцию</span> за минуты", uk:"Створіть <span class=\"gradient\">бізнес-концепцію</span> за хвилини" },
hero_desc: { be:"SVITA генеруе поўную бізнес-мадэль: памяшканні, персанал, абсталяванне, паслугі, фінансы і юрыдычныя дакументы для любой еўрапейскай краіны.", de:"SVITA generiert ein komplettes Geschäftsmodell: Räume, Personal, Ausstattung, Dienstleistungen, Finanzen und Rechtsdokumente für jedes europäische Land.", en:"SVITA generates a complete business model: premises, staff, equipment, services, financials and legal docs for any European country.", es:"SVITA genera un modelo de negocio completo: locales, personal, equipos, servicios, finanzas y documentos legales para cualquier país europeo.", fr:"SVITA génère un modèle d'affaires complet : locaux, personnel, équipements, services, finances et documents légaux pour tout pays européen.", it:"SVITA genera un modello di business completo: locali, personale, attrezzature, servizi, finanze e documenti legali per qualsiasi paese europeo.", ja:"SVITAはヨーロッパ各国向けの完全なビジネスモデルを生成：施設、スタッフ、設備、サービス、財務、法的文書。", ko:"SVITA는 유럽 모든 국가를 위한 완전한 비즈니스 모델을 생성: 시설, 직원, 장비, 서비스, 재무, 법률 문서.", pl:"SVITA generuje kompletny model biznesowy: lokale, personel, wyposażenie, usługi, finanse i dokumenty prawne dla każdego kraju europejskiego.", pt:"SVITA gera um modelo de negócio completo: instalações, equipe, equipamentos, serviços, finanças e documentação legal para qualquer país europeu.", ru:"SVITA генерирует полную бизнес-модель: помещения, персонал, оборудование, услуги, финансы и юридические документы для любой европейской страны.", uk:"SVITA генерує повну бізнес-модель: приміщення, персонал, обладнання, послуги, фінанси та юридичні документи для будь-якої європейської країни." },
hero_cta: { be:"Пачаць бясплатна", de:"Kostenlos starten", en:"Start free", es:"Empezar gratis", fr:"Commencer gratuit", it:"Inizia gratis", ja:"無料で始める", ko:"무료 시작", pl:"Zacznij za darmo", pt:"Começar grátis", ru:"Начать бесплатно", uk:"Почати безкоштовно" },
stat_stages: { be:"Этапаў канструктара", de:"Konstruktorstufen", en:"Constructor stages", es:"Etapas del constructor", fr:"Étapes du constructeur", it:"Fasi del costruttore", ja:"構築ステージ", ko:"생성 단계", pl:"Etapów konstruktora", pt:"Etapas do construtor", ru:"Этапов конструктора", uk:"Етапів конструктора" },
stat_countries: { be:"Краін Еўропы", de:"Europäische Länder", en:"European countries", es:"Países europeos", fr:"Pays européens", it:"Paesi europei", ja:"ヨーロッパ諸国", ko:"유럽 국가", pl:"Krajów Europy", pt:"Países europeus", ru:"Стран Европы", uk:"Країн Європи" },
stat_ai: { be:"AI аналітыка", de:"KI-Analyse", en:"Powered analysis", es:"Análisis con IA", fr:"Analyse IA", it:"Analisi AI", ja:"AI分析", ko:"AI 분석", pl:"Analiza AI", pt:"Análise com IA", ru:"AI-аналитика", uk:"AI-аналітика" },

// ── FEATURES ──
feat_label: { be:"Магчымасці", de:"Funktionen", en:"Features", es:"Funciones", fr:"Fonctionnalités", it:"Funzionalità", ja:"機能", ko:"기능", pl:"Funkcje", pt:"Recursos", ru:"Возможности", uk:"Можливості" },
feat_title: { be:"Усё для запуску бізнесу", de:"Alles für den Geschäftsstart", en:"Everything to launch a business", es:"Todo para lanzar un negocio", fr:"Tout pour lancer un business", it:"Tutto per lanciare un business", ja:"ビジネス立ち上げの全て", ko:"비즈니스 런칭에 필요한 모든 것", pl:"Wszystko do uruchomienia biznesu", pt:"Tudo para lançar um negócio", ru:"Всё для запуска бизнеса", uk:"Все для запуску бізнесу" },
feat_sub: { be:"Ад планіроўкі да разліку ROI — SVITA бярэ складанасць на сябе, каб вы маглі сканцэнтравацца на бачанні.", de:"Von der Raumplanung bis zur ROI-Berechnung — SVITA übernimmt die Komplexität.", en:"From premises layout to ROI calculations — SVITA handles the complexity so you can focus on your vision.", es:"Del diseño de locales al cálculo de ROI — SVITA maneja la complejidad para que te concentres en tu visión.", fr:"De l'aménagement au calcul du ROI — SVITA gère la complexité pour que vous puissiez vous concentrer sur votre vision.", it:"Dalla planificazione al calcolo del ROI — SVITA gestisce la complessità per permetterti di concentrarti sulla tua visione.", ja:"施設レイアウトからROI計算まで — SVITAが複雑さを処理し、あなたはビジョンに集中できます。", ko:"시설 레이아웃부터 ROI 계산까지 — SVITA가 복잡함을 처리하여 비전에 집중할 수 있습니다.", pl:"Od planowania lokalu po obliczenia ROI — SVITA zajmuje się złożonością, abyś mógł skupić się na wizji.", pt:"Do layout do local ao cálculo de ROI — SVITA cuida da complexidade para você focar na sua visão.", ru:"От планировки до расчёта ROI — SVITA берёт сложность на себя, чтобы вы могли сосредоточиться на видении.", uk:"Від планування до розрахунку ROI — SVITA бере складність на себе, щоб ви могли зосередитись на баченні." },
f1_t: { be:"Канструктар памяшканняў", de:"Raumkonstruktor", en:"Premises Constructor", es:"Constructor de locales", fr:"Constructeur de locaux", it:"Costruttore locali", ja:"施設コンストラクター", ko:"시설 생성기", pl:"Konstruktor lokali", pt:"Construtor de instalações", ru:"Конструктор помещений", uk:"Конструктор приміщень" },
f1_d: { be:"Планіроўка зон, разлік плошчаў, інжынерныя сеткі — з улікам санітарных нормаў.", de:"Zonenplanung, Flächenberechnung, technische Netze — konform mit Hygienestandards.", en:"Zone planning, area calculation, engineering networks — compliant with local sanitary standards.", es:"Planificación de zonas, cálculo de áreas, redes de ingeniería — conforme a normativas sanitarias.", fr:"Planification des zones, calcul des surfaces, réseaux techniques — conforme aux normes sanitaires.", it:"Pianificazione zone, calcolo superfici, reti ingegneristiche — conformi agli standard sanitari.", ja:"ゾーン計画、面積計算、エンジニアリングネットワーク — 衛生基準準拠。", ko:"구역 계획, 면적 계산, 엔지니어링 네트워크 — 위생 기준 준수.", pl:"Planowanie stref, obliczanie powierzchni, sieci inżynieryjne — zgodne z normami sanitarnymi.", pt:"Planejamento de zonas, cálculo de áreas, redes de engenharia — em conformidade com normas sanitárias.", ru:"Планировка зон, расчёт площадей, инженерные сети — с учётом санитарных норм.", uk:"Планування зон, розрахунок площ, інженерні мережі — з урахуванням санітарних норм." },
f2_t: { be:"Планаванне персаналу", de:"Personalplanung", en:"Staff Planning", es:"Planificación de personal", fr:"Planification du personnel", it:"Pianificazione personale", ja:"スタッフ計画", ko:"직원 계획", pl:"Planowanie personelu", pt:"Planejamento de equipe", ru:"Штатное расписание", uk:"Планування персоналу" },
f2_d: { be:"План найму, разлік ФАП, пасадовыя абавязкі па стандартах краіны.", de:"Einstellungsplan, Lohnberechnung, Stellenbeschreibungen nach Landesstandards.", en:"Hiring plan, payroll calculation, job descriptions following country-specific labor regulations.", es:"Plan de contratación, cálculo de nóminas, descripciones de puestos según regulaciones laborales del país.", fr:"Plan de recrutement, calcul de la masse salariale, fiches de poste selon la réglementation du pays.", it:"Piano assunzioni, calcolo stipendi, mansioni secondo le normative lavorative del paese.", ja:"採用計画、給与計算、各国の労働規制に準拠した職務記述書。", ko:"채용 계획, 급여 계산, 국가별 노동 규정에 따른 직무 기술서.", pl:"Plan rekrutacji, kalkulacja wynagrodzeń, opisy stanowisk zgodne z przepisami kraju.", pt:"Plano de contratação, cálculo de folha de pagamento, descrições de cargos conforme regulamentações trabalhistas.", ru:"План найма, расчёт ФОТ, должностные обязанности по стандартам страны.", uk:"План найму, розрахунок ФОП, посадові обов'язки за стандартами країни." },
f3_t: { be:"Каталог абсталявання", de:"Gerätekatalog", en:"Equipment Catalog", es:"Catálogo de equipos", fr:"Catalogue d'équipements", it:"Catalogo attrezzature", ja:"設備カタログ", ko:"장비 카탈로그", pl:"Katalog wyposażenia", pt:"Catálogo de equipamentos", ru:"Каталог оборудования", uk:"Каталог обладнання" },
f3_d: { be:"База пастаўшчыкоў з рэальнымі цэнамі, спецыфікацыямі, гарантыямі і тэрмінамі дастаўкі.", de:"Lieferantendatenbank mit aktuellen Preisen, Spezifikationen, Garantien und Lieferzeiten.", en:"Supplier database with real prices, specifications, warranties and delivery timelines.", es:"Base de datos de proveedores con precios reales, especificaciones, garantías y plazos de entrega.", fr:"Base de données fournisseurs avec prix réels, spécifications, garanties et délais de livraison.", it:"Database fornitori con prezzi reali, specifiche, garanzie e tempi di consegna.", ja:"サプライヤーデータベース：実際の価格、仕様、保証、納期。", ko:"공급업체 데이터베이스: 실제 가격, 사양, 보증, 납기.", pl:"Baza dostawców z realnymi cenami, specyfikacjami, gwarancjami i terminami dostaw.", pt:"Base de dados de fornecedores com preços reais, especificações, garantias e prazos de entrega.", ru:"База поставщиков с актуальными ценами, спецификациями, гарантиями и сроками поставки.", uk:"База постачальників з актуальними цінами, специфікаціями, гарантіями та термінами постачання." },
f4_t: { be:"Фінансавая мадэль", de:"Finanzmodell", en:"Financial Model", es:"Modelo financiero", fr:"Modèle financier", it:"Modello finanziario", ja:"財務モデル", ko:"재무 모델", pl:"Model finansowy", pt:"Modelo financeiro", ru:"Финансовая модель", uk:"Фінансова модель" },
f4_d: { be:"Разбіўка бюджэту, аналіз рэнтабельнасці, ROI, тэрмін акупнасці — поўнасцю аўтаматызавана.", de:"Budgetaufschlüsselung, Rentabilitätsanalyse, ROI, Amortisationszeit — vollautomatisch.", en:"Budget breakdown, profitability analysis, ROI calculation, payback period — fully automated.", es:"Desglose presupuestario, análisis de rentabilidad, cálculo de ROI, período de recuperación — totalmente automatizado.", fr:"Ventilation budgétaire, analyse de rentabilité, calcul du ROI, période de retour — entièrement automatisé.", it:"Ripartizione budget, analisi redditività, calcolo ROI, periodo di recupero — completamente automatizzato.", ja:"予算内訳、収益性分析、ROI計算、回収期間 — 完全自動化。", ko:"예산 분석, 수익성 분석, ROI 계산, 회수 기간 — 완전 자동화.", pl:"Podział budżetu, analiza rentowności, obliczenie ROI, okres zwrotu — w pełni zautomatyzowane.", pt:"Detalhamento de orçamento, análise de rentabilidade, cálculo de ROI, período de retorno — totalmente automatizado.", ru:"Разбивка бюджета, анализ рентабельности, расчёт ROI, срок окупаемости — полностью автоматизировано.", uk:"Розбивка бюджету, аналіз рентабельності, розрахунок ROI, термін окупності — повністю автоматизовано." },
f5_t: { be:"Юрыдычная адпаведнасць", de:"Recht & Compliance", en:"Legal & Compliance", es:"Legal y cumplimiento", fr:"Juridique & conformité", it:"Legale & conformità", ja:"法務・コンプライアンス", ko:"법률 및 규정 준수", pl:"Prawo i zgodność", pt:"Jurídico e conformidade", ru:"Юридическая документация", uk:"Юридична відповідність" },
f5_d: { be:"Ліцэнзіі, дазволы, санітарныя праверкі — чэк-лісты пад кожную еўрапейскую краіну.", de:"Lizenzen, Genehmigungen, Gesundheitsprüfungen — Checklisten für jedes europäische Land.", en:"Licenses, permits, health inspections — checklists tailored to each European country.", es:"Licencias, permisos, inspecciones sanitarias — checklists adaptadas a cada país europeo.", fr:"Licences, permis, inspections sanitaires — checklists adaptées à chaque pays européen.", it:"Licenze, permessi, ispezioni sanitarie — checklist personalizzate per ogni paese europeo.", ja:"ライセンス、許可証、衛生検査 — 各ヨーロッパ諸国向けチェックリスト。", ko:"라이선스, 허가, 위생 검사 — 각 유럽 국가에 맞는 체크리스트.", pl:"Licencje, pozwolenia, kontrole sanitarne — checklisty dostosowane do każdego kraju europejskiego.", pt:"Licenças, alvarás, inspeções sanitárias — checklists adaptadas a cada país europeu.", ru:"Лицензии, разрешения, санитарные проверки — чек-листы под каждую европейскую страну.", uk:"Ліцензії, дозволи, санітарні перевірки — чек-листи під кожну європейську країну." },
f6_t: { be:"AI-дарадца", de:"KI-Berater", en:"AI Advisor", es:"Asesor IA", fr:"Conseiller IA", it:"Consulente AI", ja:"AIアドバイザー", ko:"AI 어드바이저", pl:"Doradca AI", pt:"Consultor IA", ru:"AI-советник", uk:"AI-радник" },
f6_d: { be:"SVITA AI аналізуе канцэпцыю, знаходзіць рызыкі і прапануе аптымізацыі на аснове рынкавых дадзеных.", de:"SVITA AI analysiert Ihr Konzept, findet Risiken und schlägt Optimierungen auf Basis von Marktdaten vor.", en:"SVITA AI analyzes your concept, finds risks and suggests optimizations based on market data.", es:"SVITA AI analiza tu concepto, encuentra riesgos y sugiere optimizaciones basadas en datos de mercado.", fr:"SVITA AI analyse votre concept, identifie les risques et suggère des optimisations basées sur les données du marché.", it:"SVITA AI analizza il tuo concetto, trova rischi e suggerisce ottimizzazioni basate sui dati di mercato.", ja:"SVITA AIがコンセプトを分析し、リスクを発見し、市場データに基づく最適化を提案。", ko:"SVITA AI가 컨셉을 분석하고, 위험을 찾고, 시장 데이터 기반 최적화를 제안.", pl:"SVITA AI analizuje koncepcję, znajduje ryzyka i sugeruje optymalizacje na podstawie danych rynkowych.", pt:"SVITA AI analisa seu conceito, encontra riscos e sugere otimizações baseadas em dados de mercado.", ru:"SVITA AI анализирует концепцию, находит риски и предлагает оптимизации на основе рыночных данных.", uk:"SVITA AI аналізує концепцію, знаходить ризики та пропонує оптимізації на основі ринкових даних." },

// ── HOW IT WORKS ──
how_label: { be:"Як гэта працуе", de:"So funktioniert's", en:"How it works", es:"Cómo funciona", fr:"Comment ça marche", it:"Come funziona", ja:"仕組み", ko:"작동 방식", pl:"Jak to działa", pt:"Como funciona", ru:"Как это работает", uk:"Як це працює" },
how_title: { be:"Тры крокі да бізнес-плана", de:"Drei Schritte zum Businessplan", en:"Three steps to your business plan", es:"Tres pasos para tu plan de negocio", fr:"Trois étapes vers votre business plan", it:"Tre passi verso il tuo business plan", ja:"ビジネスプランへの3ステップ", ko:"비즈니스 플랜까지 3단계", pl:"Trzy kroki do biznesplanu", pt:"Três passos para seu plano de negócios", ru:"Три шага к бизнес-плану", uk:"Три кроки до бізнес-плану" },
how_sub: { be:"Досвед не патрэбны. Наш AI бярэ на сябе даследаванні, разлікі і праверку адпаведнасці.", de:"Keine Erfahrung nötig. Unsere KI übernimmt Recherche, Berechnungen und Compliance-Prüfungen.", en:"No expertise required. Our AI handles the research, calculations and compliance checks.", es:"No se requiere experiencia. Nuestra IA se encarga de la investigación, cálculos y verificación de cumplimiento.", fr:"Aucune expertise requise. Notre IA gère la recherche, les calculs et les vérifications de conformité.", it:"Nessuna esperienza richiesta. La nostra AI gestisce ricerca, calcoli e verifiche di conformità.", ja:"専門知識不要。AIがリサーチ、計算、コンプライアンスチェックを担当。", ko:"전문 지식 불필요. AI가 조사, 계산, 규정 준수 확인을 처리.", pl:"Doświadczenie nie jest wymagane. Nasz AI zajmuje się badaniami, obliczeniami i weryfikacją zgodności.", pt:"Sem necessidade de expertise. Nossa IA cuida da pesquisa, cálculos e verificações de conformidade.", ru:"Опыт не нужен. Наш AI берёт на себя исследования, расчёты и проверку соответствия.", uk:"Досвід не потрібен. Наш AI бере на себе дослідження, розрахунки та перевірку відповідності." },
s1_t: { be:"Задайце параметры", de:"Parameter festlegen", en:"Set Parameters", es:"Configura parámetros", fr:"Définissez les paramètres", it:"Imposta i parametri", ja:"パラメータを設定", ko:"매개변수 설정", pl:"Ustaw parametry", pt:"Defina os parâmetros", ru:"Задайте параметры", uk:"Задайте параметри" },
s1_d: { be:"Абярыце тып бізнесу, горад, плошчу, бюджэт і мэтавы сегмент — AI-канструктар зробіць астатняе.", de:"Wählen Sie Geschäftstyp, Stadt, Fläche, Budget und Zielsegment — der KI-Konstruktor erledigt den Rest.", en:"Choose business type, city, area, budget and target segment — the AI constructor does the rest.", es:"Elige tipo de negocio, ciudad, área, presupuesto y segmento objetivo — el constructor IA hace el resto.", fr:"Choisissez le type d'activité, la ville, la surface, le budget et le segment cible — le constructeur IA fait le reste.", it:"Scegli tipo di business, città, superficie, budget e segmento target — il costruttore AI fa il resto.", ja:"ビジネスタイプ、都市、面積、予算、ターゲットセグメントを選択 — AIが残りを処理。", ko:"비즈니스 유형, 도시, 면적, 예산, 타겟 세그먼트를 선택 — AI가 나머지를 처리.", pl:"Wybierz typ biznesu, miasto, powierzchnię, budżet i segment docelowy — konstruktor AI zrobi resztę.", pt:"Escolha o tipo de negócio, cidade, área, orçamento e segmento alvo — o construtor IA faz o resto.", ru:"Выберите тип бизнеса, город, площадь, бюджет и целевой сегмент — AI-конструктор сделает остальное.", uk:"Оберіть тип бізнесу, місто, площу, бюджет і цільовий сегмент — AI-конструктор зробить решту." },
s2_t: { be:"AI генеруе канцэпцыю", de:"KI generiert Konzept", en:"AI Generates Concept", es:"IA genera el concepto", fr:"L'IA génère le concept", it:"L'AI genera il concept", ja:"AIがコンセプトを生成", ko:"AI가 컨셉 생성", pl:"AI generuje koncepcję", pt:"IA gera o conceito", ru:"AI генерирует концепцию", uk:"AI генерує концепцію" },
s2_d: { be:"SVITA будуе поўную бізнес-мадэль: памяшканні, персанал, абсталяванне, паслугі, выдаткі і дакументы.", de:"SVITA erstellt ein vollständiges Geschäftsmodell: Räume, Personal, Ausstattung, Services, Kosten und Dokumente.", en:"SVITA builds complete business model: rooms, staff, equipment, services, costs and documents.", es:"SVITA construye un modelo de negocio completo: espacios, personal, equipos, servicios, costos y documentos.", fr:"SVITA construit un modèle d'affaires complet : locaux, personnel, équipements, services, coûts et documents.", it:"SVITA costruisce un modello di business completo: spazi, personale, attrezzature, servizi, costi e documenti.", ja:"SVITAが完全なビジネスモデルを構築：部屋、スタッフ、設備、サービス、コスト、書類。", ko:"SVITA가 완전한 비즈니스 모델 구축: 공간, 직원, 장비, 서비스, 비용, 문서.", pl:"SVITA buduje kompletny model biznesowy: pomieszczenia, personel, wyposażenie, usługi, koszty i dokumenty.", pt:"SVITA constrói modelo de negócio completo: espaços, equipe, equipamentos, serviços, custos e documentos.", ru:"SVITA строит полную бизнес-модель: помещения, персонал, оборудование, услуги, расходы и документы.", uk:"SVITA будує повну бізнес-модель: приміщення, персонал, обладнання, послуги, витрати та документи." },
s3_t: { be:"Запуск і маштабаванне", de:"Starten & Skalieren", en:"Launch & Scale", es:"Lanza y escala", fr:"Lancez et développez", it:"Lancia e scala", ja:"ローンチ＆スケール", ko:"런칭 & 확장", pl:"Uruchom i skaluj", pt:"Lance e escale", ru:"Запуск и масштабирование", uk:"Запуск і масштабування" },
s3_d: { be:"Спампуйце бізнес-план, падзяліцеся з інвестарамі і пачніце будаваць бізнес мары.", de:"Laden Sie Ihren Businessplan herunter, teilen Sie ihn mit Investoren und starten Sie Ihr Traumgeschäft.", en:"Download your business plan, share with investors, and start building your dream business.", es:"Descarga tu plan de negocio, compártelo con inversores y comienza a construir tu negocio soñado.", fr:"Téléchargez votre business plan, partagez-le avec les investisseurs et lancez votre projet rêvé.", it:"Scarica il tuo business plan, condividilo con gli investitori e inizia a costruire il tuo business dei sogni.", ja:"ビジネスプランをダウンロードし、投資家と共有し、夢のビジネスを始めましょう。", ko:"비즈니스 플랜을 다운로드하고, 투자자와 공유하고, 꿈의 비즈니스를 시작하세요.", pl:"Pobierz biznesplan, podziel się z inwestorami i zacznij budować biznes marzeń.", pt:"Baixe seu plano de negócios, compartilhe com investidores e comece a construir seu negócio dos sonhos.", ru:"Скачайте бизнес-план, поделитесь с инвесторами и начните строить бизнес мечты.", uk:"Завантажте бізнес-план, поділіться з інвесторами та почніть будувати бізнес мрії." },

// ── DOMAINS ──
dom_label: { be:"Дамены", de:"Branchen", en:"Domains", es:"Sectores", fr:"Secteurs", it:"Settori", ja:"業種", ko:"업종", pl:"Branże", pt:"Setores", ru:"Домены", uk:"Домени" },
dom_title: { be:"Які бізнес стварыць?", de:"Welches Geschäft gründen?", en:"What business to build?", es:"¿Qué negocio crear?", fr:"Quel business créer ?", it:"Quale business creare?", ja:"どのビジネスを作る？", ko:"어떤 비즈니스를 만들까?", pl:"Jaki biznes stworzyć?", pt:"Qual negócio criar?", ru:"Какой бизнес создать?", uk:"Який бізнес створити?" },
dom_sub: { be:"SVITA падтрымлівае розныя галіны з спецыялізаванымі базамі ведаў.", de:"SVITA unterstützt mehrere Branchen mit spezialisierten Wissensdatenbanken.", en:"SVITA supports multiple industries with specialized knowledge bases for each domain.", es:"SVITA soporta múltiples industrias con bases de conocimiento especializadas.", fr:"SVITA prend en charge plusieurs secteurs avec des bases de connaissances spécialisées.", it:"SVITA supporta molteplici settori con basi di conoscenza specializzate.", ja:"SVITAは各業種向けの専門知識ベースで複数の業界をサポート。", ko:"SVITA는 각 업종별 전문 지식 베이스로 다양한 산업을 지원.", pl:"SVITA wspiera wiele branż ze specjalistycznymi bazami wiedzy.", pt:"SVITA suporta múltiplas indústrias com bases de conhecimento especializadas.", ru:"SVITA поддерживает различные отрасли со специализированными базами знаний.", uk:"SVITA підтримує різні галузі зі спеціалізованими базами знань." },
d1_t: { be:"Стаматалогія", de:"Zahnarztpraxis", en:"Dental Clinics", es:"Clínicas dentales", fr:"Cabinets dentaires", it:"Cliniche dentali", ja:"歯科クリニック", ko:"치과 클리닉", pl:"Kliniki dentystyczne", pt:"Clínicas dentárias", ru:"Стоматология", uk:"Стоматологія" },
d1_d: { be:"Сямейная, дзіцячая, артадонтыя", de:"Familie, Kinder, Kieferorthopädie", en:"Family, pediatric, orthodontics", es:"Familiar, pediátrica, ortodoncia", fr:"Familiale, pédiatrique, orthodontie", it:"Familiare, pediatrica, ortodonzia", ja:"ファミリー、小児、矯正", ko:"가족, 소아, 교정", pl:"Rodzinna, dziecięca, ortodoncja", pt:"Familiar, pediátrica, ortodontia", ru:"Семейная, детская, ортодонтия", uk:"Сімейна, дитяча, ортодонтія" },
d2_t: { be:"Кавярня", de:"Café", en:"Coffee & Cafe", es:"Cafetería", fr:"Café", it:"Caffetteria", ja:"カフェ", ko:"카페", pl:"Kawiarnia", pt:"Cafeteria", ru:"Кофейня", uk:"Кав'ярня" },
d2_d: { be:"Specialty, to-go, кандытарская", de:"Specialty, To-go, Konditorei", en:"Specialty, to-go, bakery", es:"Especialidad, para llevar, pastelería", fr:"Spécialité, à emporter, pâtisserie", it:"Specialty, take-away, pasticceria", ja:"スペシャルティ、テイクアウト、ベーカリー", ko:"스페셜티, 테이크아웃, 베이커리", pl:"Specialty, na wynos, cukiernia", pt:"Especial, para viagem, confeitaria", ru:"Specialty, to-go, кондитерская", uk:"Specialty, to-go, кондитерська" },
d3_t: { be:"Салон прыгажосці", de:"Schönheitssalon", en:"Beauty Salon", es:"Salón de belleza", fr:"Salon de beauté", it:"Salone di bellezza", ja:"ビューティーサロン", ko:"뷰티 살롱", pl:"Salon urody", pt:"Salão de beleza", ru:"Салон красоты", uk:"Салон краси" },
d3_d: { be:"Прэміум, барбершоп, SPA", de:"Premium, Barbershop, SPA", en:"Premium, barbershop, SPA", es:"Premium, barbería, SPA", fr:"Premium, barbershop, SPA", it:"Premium, barbershop, SPA", ja:"プレミアム、バーバーショップ、スパ", ko:"프리미엄, 바버샵, 스파", pl:"Premium, barbershop, SPA", pt:"Premium, barbearia, SPA", ru:"Premium, барбершоп, SPA", uk:"Premium, барбершоп, SPA" },
d4_t: { be:"Рэстаран", de:"Restaurant", en:"Restaurant", es:"Restaurante", fr:"Restaurant", it:"Ristorante", ja:"レストラン", ko:"레스토랑", pl:"Restauracja", pt:"Restaurante", ru:"Ресторан", uk:"Ресторан" },
d4_d: { be:"Fine dining, фастфуд, кейтарынг", de:"Fine Dining, Fast Food, Catering", en:"Fine dining, fast food, catering", es:"Alta cocina, comida rápida, catering", fr:"Gastronomie, restauration rapide, traiteur", it:"Alta cucina, fast food, catering", ja:"ファインダイニング、ファストフード、ケータリング", ko:"파인 다이닝, 패스트푸드, 케이터링", pl:"Fine dining, fast food, catering", pt:"Fine dining, fast food, catering", ru:"Fine dining, фастфуд, кейтеринг", uk:"Fine dining, фастфуд, кейтерінг" },

// ── GEOGRAPHY ──
geo_label: { be:"Геаграфія", de:"Geografie", en:"Geography", es:"Geografía", fr:"Géographie", it:"Geografia", ja:"地理", ko:"지역", pl:"Geografia", pt:"Geografia", ru:"География", uk:"Географія" },
geo_title: { be:"Уся Еўропа, 12 валют", de:"Ganz Europa, 12 Währungen", en:"All of Europe, 12 currencies", es:"Toda Europa, 12 monedas", fr:"Toute l'Europe, 12 devises", it:"Tutta Europa, 12 valute", ja:"ヨーロッパ全土、12通貨", ko:"유럽 전역, 12개 통화", pl:"Cała Europa, 12 walut", pt:"Toda Europa, 12 moedas", ru:"Вся Европа, 12 валют", uk:"Вся Європа, 12 валют" },

// ── CTA ──
cta_title: { be:"Гатовы стварыць канцэпцыю?", de:"Bereit, Ihr Konzept zu erstellen?", en:"Ready to build your concept?", es:"¿Listo para crear tu concepto?", fr:"Prêt à créer votre concept ?", it:"Pronto a creare il tuo concept?", ja:"コンセプトを作る準備はできましたか？", ko:"컨셉을 만들 준비가 되셨나요?", pl:"Gotowy stworzyć koncepcję?", pt:"Pronto para criar seu conceito?", ru:"Готовы создать концепцию?", uk:"Готові створити концепцію?" },
cta_desc: { be:"Стварыце першую бізнес-канцэпцыю бясплатна. Без карты, без абмежаванняў.", de:"Erstellen Sie Ihr erstes Geschäftskonzept kostenlos. Keine Karte, keine Limits.", en:"Create your first business concept for free. No card required, no limits on your first project.", es:"Crea tu primer concepto de negocio gratis. Sin tarjeta, sin límites en tu primer proyecto.", fr:"Créez votre premier concept gratuitement. Sans carte, sans limites sur votre premier projet.", it:"Crea il tuo primo concept gratuitamente. Nessuna carta richiesta, nessun limite sul primo progetto.", ja:"最初のビジネスコンセプトを無料で作成。カード不要、最初のプロジェクトに制限なし。", ko:"첫 번째 비즈니스 컨셉을 무료로 만드세요. 카드 불필요, 첫 프로젝트 제한 없음.", pl:"Stwórz pierwszą koncepcję biznesową za darmo. Bez karty, bez ograniczeń.", pt:"Crie seu primeiro conceito de negócio gratuitamente. Sem cartão, sem limites no primeiro projeto.", ru:"Создайте первую бизнес-концепцию бесплатно. Без карты, без ограничений.", uk:"Створіть першу бізнес-концепцію безкоштовно. Без карти, без обмежень." },
cta_btn: { be:"Пачаць стварэнне", de:"Jetzt erstellen", en:"Start building", es:"Empezar a crear", fr:"Commencer à créer", it:"Inizia a creare", ja:"構築を始める", ko:"구축 시작", pl:"Zacznij tworzyć", pt:"Começar a criar", ru:"Начать создание", uk:"Почати створення" },

};

// ── Cross-domain lang sync via cookie (.svita.ai) ──
window.onLangChange = function(lang) {
  document.cookie = 'svita_lang=' + lang + ';path=/;max-age=31536000;domain=.svita.ai;SameSite=Lax';
};
// Read cookie on init — if user came from dashboard with a different lang
(function(){
  var m = document.cookie.match(/(?:^|;\s*)svita_lang=([a-z]{2})/);
  if (m && m[1] && window.labs67i18n && m[1] !== window.labs67i18n.getLang()) {
    window.labs67i18n.setLang(m[1]);
  }
})();
