// SVITA — Plan otwarcia kliniki stomatologicznej w Polsce
// PIVOT 2026-04-13 v2: dental PL, team-led, partner medyczny = implantolog
// Languages: PL (base) + EN (expat dentists) + BE/UK (diaspora dentists)
// All claims must be verifiable. No fake stats, no fake numbers.
// BE: no russianisms (planavany, tvaim, juryst — not planuemy/tvim/pravavy)

window.LABS67_DEFAULT_LANG = 'pl';

window.I18N = {

// ── NAV ──
nav_what:     { pl:"Co dostajesz",     en:"What you get",        be:"Што атрымліваеш",       uk:"Що отримуєш" },
nav_team:     { pl:"Zespół",           en:"Team",                be:"Каманда",               uk:"Команда" },
nav_case:     { pl:"Świtlica",         en:"Świtlica",            be:"Świtlica",              uk:"Świtlica" },
nav_pricing:  { pl:"Cennik",           en:"Pricing",             be:"Цэны",                  uk:"Ціни" },
nav_faq:      { pl:"FAQ",              en:"FAQ",                 be:"FAQ",                   uk:"FAQ" },
nav_login:    { pl:"Zaloguj",          en:"Log in",              be:"Увайсці",               uk:"Увійти" },
nav_start:    { pl:"Umów rozmowę",     en:"Book a call",         be:"Запісацца на размову",  uk:"Записатись на розмову" },

// ── HERO ──
hero_badge:   { pl:"Zespół 8 stomatologów · Polska · dane 2026",
                en:"Team of 8 dentists · Poland · 2026 data",
                be:"Каманда 8 стаматолагаў · Польшча · даныя 2026",
                uk:"Команда 8 стоматологів · Польща · дані 2026" },
hero_title:   { pl:"Plan otwarcia kliniki stomatologicznej <span class=\"gradient\">w Polsce</span> — od zespołu lekarzy",
                en:"A plan for opening a dental practice <span class=\"gradient\">in Poland</span> — built by a team of dentists",
                be:"План адкрыцця стаматалагічнай клінікі <span class=\"gradient\">ў Польшчы</span> — ад каманды лекараў",
                uk:"План відкриття стоматологічної клініки <span class=\"gradient\">у Польщі</span> — від команди лікарів" },
hero_desc:    { pl:"Zespół ośmiu stomatologów różnych specjalizacji, z partnerem medycznym — chirurgiem-implantologiem. Budujemy własną klinikę Świtlica w Bydgoszczy i dzielimy się każdym krokiem: liczbami, dostawcami, dokumentami. Zacznij od bezpłatnej rozmowy z lekarzem z zespołu.",
                en:"A team of eight dentists across different specializations, led by a medical partner — an oral surgeon-implantologist. We're building our own clinic (Świtlica, Bydgoszcz) and we share every step: numbers, suppliers, documents. Start with a free call with a doctor from the team.",
                be:"Каманда васьмі стаматолагаў розных спецыялізацый, з медычным партнёрам — хірургам-імплантолагам. Будуем уласную клініку Świtlica ў Быдгашчы і дзелімся кожным крокам: лічбамі, пастаўшчыкамі, дакументамі. Пачні з бясплатнай размовы з лекарам з каманды.",
                uk:"Команда восьми стоматологів різних спеціалізацій, з медичним партнером — хірургом-імплантологом. Будуємо власну клініку Świtlica у Бидгощі й ділимось кожним кроком: цифрами, постачальниками, документами. Почни з безкоштовної розмови з лікарем з команди." },
hero_cta:     { pl:"Umów bezpłatną rozmowę",
                en:"Book a free call",
                be:"Запісацца на бясплатную размову",
                uk:"Записатись на безкоштовну розмову" },
hero_cta_sub: { pl:"30 minut · bez zobowiązań · z lekarzem z zespołu",
                en:"30 minutes · no commitment · with a doctor from the team",
                be:"30 хвілін · без абавязацельстваў · з лекарам з каманды",
                uk:"30 хвилин · без зобов'язань · з лікарем з команди" },
hero_cta_alt: { pl:"Zobacz cennik",
                en:"See pricing",
                be:"Глянуць цэны",
                uk:"Подивитись ціни" },

// ── HERO STATS ──
stat1_v: { pl:"8",    en:"8",    be:"8",    uk:"8"    },
stat1_l: { pl:"stomatologów w zespole",    en:"dentists on the team",          be:"стаматолагаў у камандзе",           uk:"стоматологів у команді" },
stat2_v: { pl:"1",    en:"1",    be:"1",    uk:"1"    },
stat2_l: { pl:"chirurg-implantolog (PWZ)", en:"oral surgeon-implantologist (PWZ)", be:"хірург-імплантолаг (PWZ)",     uk:"хірург-імплантолог (PWZ)" },
stat3_v: { pl:"2026", en:"2026", be:"2026", uk:"2026" },
stat3_l: { pl:"rok otwarcia Świtlicy",     en:"Świtlica opening year",         be:"год адкрыцця Świtlicy",             uk:"рік відкриття Świtlicy" },

// ── TEAM SECTION ──
team_label:   { pl:"Zespół medyczny",     en:"Medical team",         be:"Медычная каманда",        uk:"Медична команда" },
team_title:   { pl:"Ośmioro lekarzy, jedna klinika",
                en:"Eight doctors, one clinic",
                be:"Восем лекараў, адна клініка",
                uk:"Восьмеро лікарів, одна клініка" },
team_sub:     { pl:"SVITA nie jest zrobiona przez programistów sprzedających dentystom. Tworzymy ją wspólnie — lekarze, którzy otwierają własną klinikę, dzielą się każdą decyzją, każdą fakturą, każdym wnioskiem do urzędu.",
                en:"SVITA isn't built by developers selling to dentists. We build it together — doctors opening their own clinic, sharing every decision, every invoice, every government application.",
                be:"SVITA не зроблена праграмістамі, якія прадаюць стаматолагам. Мы ствараем яе разам — лекары, якія адчыняюць уласную клініку, дзеляцца кожным рашэннем, кожным рахункам, кожнай заявай у ўстанову.",
                uk:"SVITA не зроблена програмістами, які продають стоматологам. Ми створюємо її разом — лікарі, що відкривають власну клініку, діляться кожним рішенням, кожним рахунком, кожною заявою до установи." },
team_partner_badge: { pl:"Partner medyczny",  en:"Medical partner",  be:"Медычны партнёр",  uk:"Медичний партнер" },
team_partner_role:  { pl:"Chirurg-implantolog · PWZ",
                      en:"Oral surgeon-implantologist · PWZ",
                      be:"Хірург-імплантолаг · PWZ",
                      uk:"Хірург-імплантолог · PWZ" },
team_partner_desc:  { pl:"Prowadzi merytoryczną część planu: od zaopatrzenia po procedury kliniczne. Każda rekomendacja w planie jest przez niego zaakceptowana.",
                      en:"Leads the clinical side of the plan: from procurement to clinical procedures. Every recommendation in the plan goes through him.",
                      be:"Вядзе медычную частку плана: ад закупак да клінічных працэдур. Кожная рэкамендацыя ў плане ім зацверджана.",
                      uk:"Веде медичну частину плану: від закупівель до клінічних процедур. Кожна рекомендація в плані ним затверджена." },
team_member_label:  { pl:"Stomatolog · zespół SVITA",
                      en:"Dentist · SVITA team",
                      be:"Стаматолаг · каманда SVITA",
                      uk:"Стоматолог · команда SVITA" },
team_note:    { pl:"Pełna lista zespołu z fotografiami i numerami PWZ dostępna po rejestracji lub na rozmowie. Prywatność naszych lekarzy jest dla nas ważna.",
                en:"The full team list with photos and PWZ numbers is available after sign-up or on a call. We respect our doctors' privacy.",
                be:"Поўны спіс каманды з фатаграфіямі і нумарамі PWZ даступны пасля рэгістрацыі або на размове. Прыватнасць нашых лекараў для нас важная.",
                uk:"Повний список команди з фотографіями та номерами PWZ доступний після реєстрації або на розмові. Приватність наших лікарів для нас важлива." },

// ── WHAT YOU GET ──
what_label: { pl:"Co dostajesz", en:"What you get",     be:"Што атрымліваеш",    uk:"Що отримуєш" },
what_title: { pl:"6 rozdziałów twojego planu",
              en:"6 chapters of your plan",
              be:"6 раздзелаў твайго плана",
              uk:"6 розділів твого плану" },
what_sub:   { pl:"Każdy rozdział to konkretne liczby, źródła i lista zakupów — nie ogólniki. Pisane przez ludzi, którzy robią to samo u siebie.",
              en:"Every chapter has concrete numbers, sources and shopping lists — no fluff. Written by people doing the same thing themselves.",
              be:"Кожны раздзел — канкрэтныя лічбы, крыніцы і спіс закупак, без агульных слоў. Пісана людзьмі, якія робяць тое ж у сябе.",
              uk:"Кожен розділ — конкретні цифри, джерела та список закупівель, без загальних слів. Пишуть люди, що роблять те саме у себе." },

w1_t: { pl:"1. Lokal", en:"1. Premises", be:"1. Памяшканне", uk:"1. Приміщення" },
w1_d: { pl:"Minimalny metraż dla NFZ, układ pomieszczeń, wymagania sanepid, średnia stawka czynszu w wybranym mieście. Źródła: otodom.pl, raporty Colliers 2026, nasze rozmowy z pośrednikami.",
        en:"Minimum area for NFZ, room layout, sanepid requirements, average rent in your city. Sources: otodom.pl, Colliers 2026 reports, our own broker conversations.",
        be:"Мінімальная плошча для NFZ, планіроўка пакояў, патрабаванні sanepid, сярэдняя арэнда ў тваім горадзе. Крыніцы: otodom.pl, справаздачы Colliers 2026, нашы размовы з пасрэднікамі.",
        uk:"Мінімальна площа для NFZ, планування приміщень, вимоги sanepid, середня оренда у твоєму місті. Джерела: otodom.pl, звіти Colliers 2026, наші розмови з посередниками." },

w2_t: { pl:"2. Zespół i ZUS", en:"2. Team and payroll", be:"2. Каманда і ZUS", uk:"2. Команда і ZUS" },
w2_d: { pl:"Stomatolog, asystent, higienistka, recepcjonista — pensje brutto 2026 z pracuj.pl + składki ZUS i PIT. Gotowe ogłoszenia do publikacji.",
        en:"Dentist, assistant, hygienist, receptionist — gross 2026 salaries from pracuj.pl + ZUS and PIT contributions. Ready-to-publish job posts.",
        be:"Стаматолаг, асістэнт, гігіенічка, рэцэпцыяніст — заробкі брута 2026 з pracuj.pl + уплаты ZUS і PIT. Гатовыя аб'явы для публікацыі.",
        uk:"Стоматолог, асистент, гігієніст, рецепціоніст — зарплати брутто 2026 з pracuj.pl + внески ZUS і PIT. Готові оголошення для публікації." },

w3_t: { pl:"3. Sprzęt — realni dostawcy", en:"3. Equipment — real suppliers", be:"3. Абсталяванне — рэальныя пастаўшчыкі", uk:"3. Обладнання — реальні постачальники" },
w3_d: { pl:"Unit dentystyczny, RTG, autoklaw, lampa polimeryzacyjna, fotel — ceny KaVo Polska, Planmeca PL, Dentsply Sirona PL, Henry Schein, negocjowane przez partnera medycznego.",
        en:"Dental unit, X-ray, autoclave, curing light, chair — prices from KaVo Polska, Planmeca PL, Dentsply Sirona PL, Henry Schein, negotiated through our medical partner.",
        be:"Стаматалагічная ўстаноўка, RTG, аўтаклаў, лямпа палімерызацыі, крэсла — цэны KaVo Polska, Planmeca PL, Dentsply Sirona PL, Henry Schein, узгодненыя праз медычнага партнёра.",
        uk:"Стоматологічна установка, RTG, автоклав, лампа полімеризації, крісло — ціни KaVo Polska, Planmeca PL, Dentsply Sirona PL, Henry Schein, узгоджені через медичного партнера." },

w4_t: { pl:"4. Dokumenty i licencje", en:"4. Documents and licenses", be:"4. Дакументы і ліцэнзіі", uk:"4. Документи та ліцензії" },
w4_d: { pl:"Wpis do rejestru podmiotów leczniczych (RPWDL), zezwolenie PAA na RTG, decyzja sanepidu, RODO. Wzory wniosków + kontakty urzędów dla twojego województwa.",
        en:"Entry in the medical entities register (RPWDL), PAA X-ray license, sanepid decision, RODO. Application templates + office contacts for your voivodeship.",
        be:"Запіс у рэестр медычных суб'ектаў (RPWDL), дазвол PAA на RTG, рашэнне sanepid, RODO. Узоры заяў + кантакты ўстаноў для твайго ваяводства.",
        uk:"Запис до реєстру медичних суб'єктів (RPWDL), дозвіл PAA на RTG, рішення sanepid, RODO. Зразки заяв + контакти установ для твого воєводства." },

w5_t: { pl:"5. Budżet startu", en:"5. Startup budget", be:"5. Бюджэт старту", uk:"5. Бюджет старту" },
w5_d: { pl:"Rozbicie pozycja po pozycji: lokal, remont, sprzęt, dokumenty, marketing, rezerwa płynności na 3 miesiące. PLN, podatki uwzględnione.",
        en:"Line-by-line breakdown: premises, fit-out, equipment, documents, marketing, 3-month liquidity reserve. PLN, taxes included.",
        be:"Разбіўка па пазіцыях: памяшканне, рамонт, абсталяванне, дакументы, маркетынг, рэзерв на 3 месяцы. PLN, з падаткамі.",
        uk:"Розбивка по позиціях: приміщення, ремонт, обладнання, документи, маркетинг, резерв на 3 місяці. PLN, з податками." },

w6_t: { pl:"6. ROI i rentowność", en:"6. ROI and profitability", be:"6. ROI і рэнтабельнасць", uk:"6. ROI і рентабельність" },
w6_d: { pl:"Założenia: liczba pacjentów/dzień, średni koszyk, marża implantologiczna i ogólnostomatologiczna. Próg rentowności w miesiącach. Wrażliwość ±20%.",
        en:"Assumptions: patients/day, average ticket, implantology and general dental margins. Break-even in months. Sensitivity ±20%.",
        be:"Дапушчэнні: пацыентаў/дзень, сярэдні чэк, маржа імплантацыі і агульнай стаматалогіі. Парог рэнтабельнасці ў месяцах. Адчувальнасць ±20%.",
        uk:"Припущення: пацієнтів/день, середній чек, маржа імплантології та загальної стоматології. Поріг рентабельності в місяцях. Чутливість ±20%." },

// ── HONESTY ──
honesty_label: { pl:"Czego nie sprzedajemy", en:"What we won't sell you",  be:"Чаго мы не прадаём",  uk:"Чого ми не продаємо" },
honesty_title: { pl:"Czego ten plan nie zrobi", en:"What this plan won't do",  be:"Чаго гэты план не зробіць",  uk:"Чого цей план не зробить" },
honesty_sub:   { pl:"Jesteśmy zespołem, który sam otwiera klinikę. Wiemy co działa, wiemy co nie — i mówimy wprost.",
                 en:"We're a team opening a clinic ourselves. We know what works, we know what doesn't — and we say it plainly.",
                 be:"Мы каманда, якая сама адчыняе клініку. Ведаем, што працуе, ведаем, што не — і кажам адкрыта.",
                 uk:"Ми команда, що сама відкриває клініку. Знаємо, що працює, знаємо, що ні — і говоримо прямо." },
h1_t: { pl:"Nie zastąpi prawnika", en:"Won't replace a lawyer",  be:"Не заменіць юрыста",  uk:"Не замінить юриста" },
h1_d: { pl:"Każdy dokument trzeba podpisać u notariusza i sprawdzić u radcy prawnego. Plan zawiera szablony i kontakty — nie poradę prawną.",
        en:"Every document needs notarization and a lawyer's review. The plan has templates and contact lists — not legal advice.",
        be:"Кожны дакумент трэба падпісаць у натарыуса і праверыць у юрыста. План утрымлівае шаблоны і кантакты — не юрыдычную параду.",
        uk:"Кожен документ треба підписати у нотаріуса і перевірити у юриста. План містить шаблони та контакти — не юридичну пораду." },
h2_t: { pl:"Ceny mogą się zmienić", en:"Prices may shift",  be:"Цэны могуць змяніцца",  uk:"Ціни можуть змінитись" },
h2_d: { pl:"Wszystkie liczby pochodzą z konkretnych ofert na 2026-04. Każda pozycja ma datę i źródło — aktualizujemy przez 6 miesięcy od zakupu.",
        en:"Every number comes from a real 2026-04 offer. Every line item has a date and source — we update for 6 months after purchase.",
        be:"Усе лічбы — з канкрэтных прапаноў на 2026-04. Кожная пазіцыя мае дату і крыніцу — абнаўляем 6 месяцаў пасля пакупкі.",
        uk:"Усі цифри — з конкретних пропозицій на 2026-04. Кожна позиція має дату і джерело — оновлюємо 6 місяців після покупки." },
h3_t: { pl:"Nie sprzedajemy sprzętu", en:"We don't sell equipment",  be:"Мы не прадаём абсталяванне",  uk:"Ми не продаємо обладнання" },
h3_d: { pl:"Nie sprzedajemy unitów, nie wynajmujemy lokali, nie zatrudniamy ludzi za ciebie. Linkujemy bezpośrednio do producentów i pośredników.",
        en:"We don't sell dental units, lease premises or hire people for you. We link directly to manufacturers and brokers.",
        be:"Не прадаём устаноўкі, не арандуем памяшканняў, не наймаем людзей за цябе. Спасылаемся напрамую на вытворцаў і пасрэднікаў.",
        uk:"Не продаємо установки, не орендуємо приміщень, не наймаємо людей за тебе. Посилаємось напряму на виробників та посередників." },

// ── ŚWITLICA CASE ──
case_label:    { pl:"Nasz własny projekt", en:"Our own project",  be:"Наш уласны праект",  uk:"Наш власний проєкт" },
case_title:    { pl:"Świtlica — klinika zespołu SVITA w Bydgoszczy",
                 en:"Świtlica — the SVITA team's clinic in Bydgoszcz",
                 be:"Świtlica — клініка каманды SVITA ў Быдгашчы",
                 uk:"Świtlica — клініка команди SVITA у Бидгощі" },
case_sub:      { pl:"Zanim zaczęliśmy oferować plan, użyliśmy go u siebie. Klinika jest w budowie — każdą decyzję dokumentujemy na żywo. Nie marketing, tylko praca.",
                 en:"Before offering the plan, we used it on ourselves. The clinic is under construction — every decision documented live. Not marketing, just work.",
                 be:"Перш чым прапаноўваць план, мы ўжылі яго ў сябе. Клініка ў будоўлі — кожнае рашэнне дакументуем у жывым часе. Не маркетынг, а праца.",
                 uk:"Перш ніж пропонувати план, ми застосували його у себе. Клініка в будівництві — кожне рішення документуємо в прямому часі. Не маркетинг, а робота." },
case_budget:   { pl:"Planowany budżet", en:"Planned budget",  be:"Планаваны бюджэт",  uk:"Запланований бюджет" },
case_budget_v: { pl:"~1 760 000 PLN", en:"~1,760,000 PLN",  be:"~1 760 000 PLN",  uk:"~1 760 000 PLN" },
case_open:     { pl:"Planowane otwarcie", en:"Planned opening",  be:"Планаванае адкрыццё",  uk:"Заплановане відкриття" },
case_open_v:   { pl:"Wrzesień 2026", en:"September 2026",  be:"Верасень 2026",  uk:"Вересень 2026" },
case_city:     { pl:"Miasto", en:"City",  be:"Горад",  uk:"Місто" },
case_city_v:   { pl:"Bydgoszcz", en:"Bydgoszcz",  be:"Быдгашч",  uk:"Бидгощ" },
case_format:   { pl:"Format", en:"Format",  be:"Фармат",  uk:"Формат" },
case_format_v: { pl:"3 fotele · NFZ + prywatnie · implantologia",
                 en:"3 chairs · NFZ + private · implantology",
                 be:"3 крэслы · NFZ + прыватна · імплантацыя",
                 uk:"3 крісла · NFZ + приватно · імплантологія" },
case_warning:  { pl:"Klinika jeszcze się nie otworzyła. Aktualizujemy plan w miarę postępów budowy. To uczciwy work-in-progress — dokumentacja w czasie rzeczywistym, nie prezentacja sprzedażowa.",
                 en:"The clinic hasn't opened yet. We update the plan as construction progresses. Honest work-in-progress — real-time documentation, not a sales pitch.",
                 be:"Клініка яшчэ не адкрылася. Абнаўляем план па меры будоўлі. Гэта сумленны work-in-progress — дакументацыя ў жывым часе, а не прадажная прэзентацыя.",
                 uk:"Клініка ще не відкрилась. Оновлюємо план у міру будівництва. Це чесний work-in-progress — документація в прямому часі, а не продажна презентація." },

// ── PRICING (3 tiers) ──
pricing_label: { pl:"Cennik", en:"Pricing",  be:"Цэны",  uk:"Ціни" },
pricing_title: { pl:"Trzy poziomy — dla każdego etapu",
                 en:"Three tiers — one for each stage",
                 be:"Тры ўзроўні — для кожнага этапу",
                 uk:"Три рівні — для кожного етапу" },
pricing_sub:   { pl:"Zamiast trialu i 12 poziomów PRO — trzy jasne oferty. Zaczynasz od rozmowy, potem wybierasz co naprawdę potrzebne.",
                 en:"Instead of trials and 12 PRO tiers — three clear offers. Start with a call, then pick what you actually need.",
                 be:"Замест трыялаў і 12 узроўняў PRO — тры ясныя прапановы. Пачынаеш з размовы, потым выбіраеш, што сапраўды трэба.",
                 uk:"Замість тріалів та 12 рівнів PRO — три ясні пропозиції. Починаєш з розмови, потім обираєш, що справді треба." },

tier1_label:   { pl:"Audyt", en:"Audit",  be:"Аўдыт",  uk:"Аудит" },
tier1_price:   { pl:"49 €", en:"€49",  be:"49 €",  uk:"49 €" },
tier1_sub:     { pl:"jednorazowo", en:"one-time",  be:"аднаразова",  uk:"одноразово" },
tier1_desc:    { pl:"Audyt twojego pomysłu", en:"Audit of your idea",  be:"Аўдыт твайго задуму",  uk:"Аудит твоєї ідеї" },
tier1_f1:      { pl:"✓ 30-minutowa rozmowa z lekarzem z zespołu",
                 en:"✓ 30-min call with a doctor from the team",
                 be:"✓ 30-хвілінная размова з лекарам з каманды",
                 uk:"✓ 30-хвилинна розмова з лікарем з команди" },
tier1_f2:      { pl:"✓ Pisemna opinia 2 strony: czy pomysł ma sens",
                 en:"✓ 2-page written opinion: does the idea make sense",
                 be:"✓ Пісьмовы адзыў на 2 старонкі: ці мае задума сэнс",
                 uk:"✓ Письмовий висновок на 2 сторінки: чи має ідея сенс" },
tier1_f3:      { pl:"✓ 3 konkretne ryzyka dla twojego miasta",
                 en:"✓ 3 concrete risks for your city",
                 be:"✓ 3 канкрэтныя рызыкі для твайго горада",
                 uk:"✓ 3 конкретні ризики для твого міста" },
tier1_f4:      { pl:"✓ Rabat 49 € na każdy wyższy pakiet",
                 en:"✓ €49 discount on any higher tier",
                 be:"✓ Зніжка 49 € на любы старэйшы пакет",
                 uk:"✓ Знижка 49 € на будь-який вищий пакет" },
tier1_cta:     { pl:"Zamów audyt", en:"Order audit",  be:"Замовіць аўдыт",  uk:"Замовити аудит" },

tier2_label:   { pl:"Pełny plan", en:"Full plan",  be:"Поўны план",  uk:"Повний план" },
tier2_badge:   { pl:"Najpopularniejszy", en:"Most popular",  be:"Самы папулярны",  uk:"Найпопулярніший" },
tier2_price:   { pl:"1 490 €", en:"€1,490",  be:"1 490 €",  uk:"1 490 €" },
tier2_sub:     { pl:"jednorazowo", en:"one-time",  be:"аднаразова",  uk:"одноразово" },
tier2_desc:    { pl:"Pełny plan + negocjacje", en:"Full plan + negotiations",  be:"Поўны план + перамовы",  uk:"Повний план + переговори" },
tier2_f1:      { pl:"✓ 6 rozdziałów planu z liczbami i źródłami",
                 en:"✓ 6 plan chapters with numbers and sources",
                 be:"✓ 6 раздзелаў плана з лічбамі і крыніцамі",
                 uk:"✓ 6 розділів плану з цифрами та джерелами" },
tier2_f2:      { pl:"✓ Negocjacje z 3 dostawcami sprzętu w twoim imieniu",
                 en:"✓ Equipment vendor negotiations on your behalf (3 suppliers)",
                 be:"✓ Перамовы з 3 пастаўшчыкамі абсталявання ад твайго імя",
                 uk:"✓ Переговори з 3 постачальниками обладнання від твого імені" },
tier2_f3:      { pl:"✓ Osobisty opiekun — lekarz z zespołu",
                 en:"✓ Personal advisor — a doctor from the team",
                 be:"✓ Асабісты куратар — лекар з каманды",
                 uk:"✓ Особистий куратор — лікар з команди" },
tier2_f4:      { pl:"✓ Szablony dokumentów NFZ, sanepid, PAA",
                 en:"✓ Document templates: NFZ, sanepid, PAA",
                 be:"✓ Шаблоны дакументаў NFZ, sanepid, PAA",
                 uk:"✓ Шаблони документів NFZ, sanepid, PAA" },
tier2_f5:      { pl:"✓ Aktualizacje cen przez 12 miesięcy",
                 en:"✓ Price updates for 12 months",
                 be:"✓ Абнаўленні цэн на працягу 12 месяцаў",
                 uk:"✓ Оновлення цін протягом 12 місяців" },
tier2_cta:     { pl:"Wybierz plan", en:"Select plan",  be:"Выбраць план",  uk:"Обрати план" },

tier3_label:   { pl:"Partnerstwo", en:"Partnership",  be:"Партнёрства",  uk:"Партнерство" },
tier3_price:   { pl:"5 000 €", en:"€5,000",  be:"5 000 €",  uk:"5 000 €" },
tier3_sub:     { pl:"od · etapowo", en:"from · in stages",  be:"ад · этапамі",  uk:"від · етапами" },
tier3_desc:    { pl:"Prowadzenie otwarcia pod klucz", en:"Turnkey opening management",  be:"Вядзенне адкрыцця пад ключ",  uk:"Ведення відкриття під ключ" },
tier3_f1:      { pl:"✓ Wszystko z pakietu Pełny plan",
                 en:"✓ Everything in the Full plan tier",
                 be:"✓ Усё з пакета Поўны план",
                 uk:"✓ Усе з пакета Повний план" },
tier3_f2:      { pl:"✓ Wsparcie podczas remontu i zakupów",
                 en:"✓ Support during fit-out and procurement",
                 be:"✓ Падтрымка падчас рамонту і закупак",
                 uk:"✓ Підтримка під час ремонту та закупівель" },
tier3_f3:      { pl:"✓ Osobisty partner medyczny przy otwarciu",
                 en:"✓ Personal medical partner at opening",
                 be:"✓ Асабісты медычны партнёр на адкрыцці",
                 uk:"✓ Особистий медичний партнер на відкритті" },
tier3_f4:      { pl:"✓ Gwarancja: otwierasz w terminie lub zwracamy 50%",
                 en:"✓ Guarantee: open on time or we refund 50%",
                 be:"✓ Гарантыя: адкрываешся ў тэрмін або вяртаем 50%",
                 uk:"✓ Гарантія: відкриваєшся в строк або повертаємо 50%" },
tier3_cta:     { pl:"Umów rozmowę", en:"Book a call",  be:"Запісацца на размову",  uk:"Записатись на розмову" },

pricing_note:  { pl:"Każdy pakiet zaczyna się od bezpłatnej 30-minutowej rozmowy. Filtrujemy niedopasowania razem — lepiej dla wszystkich.",
                 en:"Every tier starts with a free 30-minute call. We filter misfits together — better for everyone.",
                 be:"Кожны пакет пачынаецца з бясплатнай 30-хвіліннай размовы. Адсейваем неадпаведныя выпадкі разам — лепей для ўсіх.",
                 uk:"Кожен пакет починається з безкоштовної 30-хвилинної розмови. Відсіюємо невідповідні випадки разом — краще для всіх." },

// ── FAQ ──
faq_label: { pl:"FAQ", en:"FAQ",  be:"FAQ",  uk:"FAQ" },
faq_title: { pl:"Pytania bez ściemy", en:"Questions without BS",  be:"Пытанні без туману",  uk:"Питання без туману" },
q1: { pl:"Dlaczego tylko stomatologia w Polsce?",
      en:"Why only dentistry in Poland?",
      be:"Чаму толькі стаматалогія ў Польшчы?",
      uk:"Чому тільки стоматологія в Польщі?" },
a1: { pl:"Bo jesteśmy zespołem stomatologów, sami otwieramy klinikę w Bydgoszczy. Robimy to, co znamy. Inne branże — dopiero po 10 płacących klientach w PL.",
      en:"Because we're a team of dentists opening our own clinic in Bydgoszcz. We do what we know. Other industries — only after 10 paying clients in PL.",
      be:"Бо мы каманда стаматолагаў, самі адчыняем клініку ў Быдгашчы. Робім тое, што ведаем. Іншыя галіны — толькі пасля 10 платных кліентаў у PL.",
      uk:"Бо ми команда стоматологів, самі відкриваємо клініку у Бидгощі. Робимо те, що знаємо. Інші галузі — тільки після 10 платних клієнтів у PL." },
q2: { pl:"Skąd pewność że ceny są prawdziwe?",
      en:"How do you know the prices are real?",
      be:"Адкуль пэўнасць, што цэны сапраўдныя?",
      uk:"Звідки впевненість, що ціни справжні?" },
a2: { pl:"Każda pozycja ma datę i źródło: oferta od dystrybutora, mail od handlowca, faktura z naszej własnej kliniki Świtlica. Jeśli źródła nie ma — pozycji w planie nie ma.",
      en:"Every line has a date and source: distributor offer, sales email, invoice from our own Świtlica clinic. No source, no line in the plan.",
      be:"Кожная пазіцыя мае дату і крыніцу: прапанова ад дыстрыбутара, ліст ад гандляра, рахунак з нашай уласнай клінікі Świtlica. Няма крыніцы — няма пазіцыі ў плане.",
      uk:"Кожна позиція має дату і джерело: пропозиція від дистриб'ютора, лист від продавця, рахунок з нашої власної клініки Świtlica. Немає джерела — немає позиції в плані." },
q3: { pl:"Macie inne kliniki otwarte z waszego planu?",
      en:"Do you have other clinics opened with this plan?",
      be:"Ці маеце іншыя клінікі, адкрытыя па вашым плане?",
      uk:"Чи маєте інші клініки, відкриті за вашим планом?" },
a3: { pl:"Nie. Świtlica jest pierwsza i jeszcze się otwiera (wrzesień 2026). Jesteśmy nowym zespołem i nie udajemy weteranów — ale każdy z ośmiu lekarzy ma lata własnej praktyki za sobą.",
      en:"No. Świtlica is first and still opening (September 2026). We're a new team and we don't pretend to be veterans — but each of the eight doctors has years of private practice behind them.",
      be:"Не. Świtlica — першая і яшчэ толькі адкрываецца (верасень 2026). Мы новая каманда і не ўдаём з сябе ветэранаў — але кожны з васьмі лекараў мае гады ўласнай практыкі за плячыма.",
      uk:"Ні. Świtlica — перша і ще тільки відкривається (вересень 2026). Ми нова команда і не вдаємо ветеранів — але кожен з восьми лікарів має роки власної практики за плечима." },
q4: { pl:"AI wygeneruje mi plan w godzinę?",
      en:"Will the AI generate my plan in an hour?",
      be:"Ці згенеруе мне AI план за гадзіну?",
      uk:"Чи згенерує мені AI план за годину?" },
a4: { pl:"Szkic — tak, w minutę. Pełny plan z zweryfikowanymi liczbami, rozmowami z dostawcami i listą dokumentów dla twojego województwa — 14 dni roboczych. AI pomaga, decyzje podejmują lekarze.",
      en:"Draft — yes, in a minute. Full plan with verified numbers, supplier calls and a per-voivodeship document checklist — 14 business days. AI assists, doctors decide.",
      be:"Накід — так, за хвіліну. Поўны план з правераным лічбамі, размовамі з пастаўшчыкамі і спісам дакументаў для твайго ваяводства — 14 рабочых дзён. AI дапамагае, рашэнні прымаюць лекары.",
      uk:"Начерк — так, за хвилину. Повний план з перевіреними цифрами, розмовами з постачальниками та списком документів для твого воєводства — 14 робочих днів. AI допомагає, рішення приймають лікарі." },
q5: { pl:"Co jeśli się rozmyślę?",
      en:"What if I change my mind?",
      be:"А калі я перадумаю?",
      uk:"А якщо я передумаю?" },
a5: { pl:"Dlatego zaczynamy od bezpłatnej 30-minutowej rozmowy. Filtrujemy niedopasowania przed płatnością — nie obsługujemy refund engine, tylko serio pracujemy.",
      en:"That's why we start with a free 30-minute call. We filter out misfits before payment — we don't run a refund engine, we actually work.",
      be:"Таму пачынаем з бясплатнай 30-хвіліннай размовы. Адсейваем неадпаведныя выпадкі да аплаты — мы не refund engine, мы сур'ёзна працуем.",
      uk:"Тому починаємо з безкоштовної 30-хвилинної розмови. Відсіюємо невідповідні випадки до оплати — ми не refund engine, ми серйозно працюємо." },
q6: { pl:"Kto za tym stoi?",
      en:"Who's behind this?",
      be:"Хто за гэтым стаіць?",
      uk:"Хто за цим стоїть?" },
a6: { pl:"Artem Wialko — założyciel SVITA, technolog, CEO LABS67. Partner medyczny: chirurg-implantolog z PWZ (dane na rozmowie). Zespół: 8 stomatologów różnych specjalizacji. Nie udajemy lekarzy — lekarze są obok nas i podpisują każdą rekomendację w planie.",
      en:"Artem Wialko — SVITA founder, technologist, CEO of LABS67. Medical partner: an oral surgeon-implantologist with PWZ (details on the call). Team: 8 dentists across specializations. We don't pretend to be doctors — doctors are right beside us, signing off on every recommendation in the plan.",
      be:"Artem Wialko — заснавальнік SVITA, тэхнолаг, CEO LABS67. Медычны партнёр: хірург-імплантолаг з PWZ (даныя на размове). Каманда: 8 стаматолагаў розных спецыялізацый. Мы не ўдаём з сябе лекараў — лекары побач з намі і падпісваюць кожную рэкамендацыю ў плане.",
      uk:"Artem Wialko — засновник SVITA, технолог, CEO LABS67. Медичний партнер: хірург-імплантолог з PWZ (дані на розмові). Команда: 8 стоматологів різних спеціалізацій. Ми не вдаємо лікарів — лікарі поруч з нами і підписують кожну рекомендацію в плані." },

// ── FOOTER ──
foot_tagline: { pl:"Zespół lekarzy. Jedna klinika. Jeden plan. Zero ściemy.",
                en:"Team of doctors. One clinic. One plan. Zero BS.",
                be:"Каманда лекараў. Адна клініка. Адзін план. Нуль туману.",
                uk:"Команда лікарів. Одна клініка. Один план. Нуль туману." },

};
